services:
  webserver:
    volumes:
      - moodledata:/var/www/moodledata # Runtime data
      - moodlecode:/var/www/html # Application
      # Plugins Bind-mounts
      - ./moodle/question/type:/var/www/html/question/type
      - ./moodle/local:/var/www/html/local
      # XDebug Configuration (read-only)
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
    environment:
      PHP_EXTENSION_xdebug: 1
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: yes
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
  db:
    ports:
      - "5432:5432"
    volumes:
      - moodledb:/var/lib/postgresql/data # Database

volumes:
  moodledata:
  moodledb:
  moodlecode: